vich_uploader:
    db_driver: orm

    mappings:
       produits_image:
           uri_prefix: /images/produits
           upload_destination: '%kernel.project_dir%/public/images/produits'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
