easy_admin:
  site_name: 'AnnoncePerso <em style="font-size: 80%">Backoffice</em> <span style="font-size: 20%"><a href="http://localhost:8000" style="font-size: 60%" class="text-primary">Quitter</a></span>'