easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      form:
        fields:
          - {property: 'nom'}

      list:
        actions:
          - {name: 'edit', icon: 'pencil-ruler', label: false}
          - {name: 'delete', icon: 'trash-alt', label: false}