easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - {property: 'prenom'}
          - {property: 'nom'}
          - {property: 'pseudo'}
          - {property: 'email'}
          - {property: 'ville'}
          - {property: 'civilite'}
          - {property: 'CreatedAt'}
          - {property: 'Roles', type: 'collection'}

      
      list:
        actions:
          - {name: 'edit', icon: 'pencil-ruler', label: false}
          - {name: 'delete', icon: 'trash-alt', label: false}